# ===============================
# DATABASE (PRODUCTION)
# ===============================
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=aaohNSJQORbFUfEUPOzQbotCZvuvzEjx

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false


# ===============================
# GOOGLE OAUTH (PROD)
# ===============================
spring.security.oauth2.client.registration.google.client-id=${google_client_id}
spring.security.oauth2.client.registration.google.client-secret=${google_client_secret}

# ===============================
# JWT
# ===============================
security.jwt.secret=9f3c2a4b8e1d6c7f5a9b0c3d4e2f1a6b7c8d9e0f1234567890abcdef12345678